server:
  port: 9999

client:
  baseUrl: "http://localhost:9090"

authProvider:
  jwt:
    header: Authorization
    secret: annoml


spring:
  http:
    log-request-details: true

  datasource:

    ## default connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

    ## PostgreSQL
    url: jdbc:postgresql://localhost:5432/annoml
    username: annoml
    password: AnnoML

  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

debug: true